### ISSUE TITLE
Can't add new integration (1.5.0)

### ISSUE THREAD

**Issue by thorstenhornung1** [hugobloem/stateful_scenes#147]
Good morning and thanks for the Integration.

Unfortunately after updating to 1.5.0 I can't add new scenes any more. When adding the integration I get this error

2024-12-08 07:05:53.236 WARNING (MainThread) [custom_components.stateful_scenes.config_flow] Hub.__init__() got an unexpected keyword argument 'scene_path'

Thank you very much in advance for looking nto this
Thorsten

![image](https://github.com/user-attachments/assets/a444708d-dcad-4ad6-b7fe-2f7d442e171c)

**Comment by dadiv** [comment]
I had this same issue yesterday. I downgraded to 1.4.0 and was able to complete the new install. Then I upgraded to 1.5.0 and things continue to work as expected.
